# Framework Setup Script for Vivado GUI (2025.2 Self-Healing + Bootstrap)
set board_name [lindex $argv 0]
set target_lang [lindex $argv 1]
if {$target_lang == ""} { set target_lang "VHDL" }
set part [lindex $argv 2]
if {$part == ""} { set part "xc7z010clg400-1" }

set script_path [file normalize "./board_configs/${board_name}_bd.tcl"]

# --- Pre-create project & register IP repos BEFORE sourcing the BD script ---
# The BD script (generated by write_bd_tcl) creates its own project via
# create_project when none exists yet, but that path knows nothing about
# ip_repos.txt - so custom-packaged IP (e.g. Digilent's rgb2dvi) referenced
# via create_bd_cell fails to resolve. Pre-creating the project here causes
# the BD script's own create_project call to be skipped (it checks
# [get_projects -quiet] first), so the IP catalog is already populated by
# the time it runs.
if {[get_projects -quiet] == ""} {
    create_project project_1 myproj -part $part

    set ip_repos_file "ip_repos.txt"
    set ip_repo_paths {}

    if {[file exists $ip_repos_file]} {
        puts "📖 Reading IP repositories from $ip_repos_file"
        set fp [open $ip_repos_file r]
        set lines [split [read $fp] "\n"]
        close $fp
        foreach line $lines {
            set entry [string trim $line]
            if {$entry != "" && ![string match "#*" $entry]} {
                lappend ip_repo_paths $entry
            }
        }
    } elseif {[info exists env(EXTRA_IP_REPOS)]} {
        set ip_repo_paths [split $env(EXTRA_IP_REPOS) ","]
    }

    if {[llength $ip_repo_paths] > 0} {
        puts "📦 Registering [llength $ip_repo_paths] IP repositories"
        set_property ip_repo_paths $ip_repo_paths [current_project]
        update_ip_catalog
    }

    # --- Add HDL source files (src/hdl & utilities/hdl_templates) for BD Module Reference ---
    set hdl_files [concat [glob -nocomplain "src/hdl/*.vhd" "src/hdl/*.v" "src/hdl/*.sv"] \
                          [glob -nocomplain "utilities/hdl_templates/*.vhd"]]
    if {[llength $hdl_files] > 0} {
        puts "📦 Adding [llength $hdl_files] HDL source files to project..."
        add_files -norecurse $hdl_files
    }
}

# --- THE SELF-HEALING REPAIR & BOOTSTRAP ---
proc ::sync_bd { {path ""} } {
    if {$path == ""} {
        global board_name
        set path [file normalize "./board_configs/${board_name}_bd.tcl"]
    }
    
    puts "🚀 Syncing Block Design to $path..."
    if { [catch {write_bd_tcl -force "$path"} err] } {
        puts "❌ Error syncing BD: $err"
        return
    }
    puts "✅ Block Design successfully synced!"

    # --- BOOTSTRAP TOP HDL ---
    set bd_files [get_files -quiet *.bd]
    if {$bd_files == ""} {
        puts "⚠️  No Block Design found in project. Skipping bootstrap."
        return
    }

    # Generate the wrapper to get the port list
    puts "🔨 Generating wrapper for [lindex $bd_files 0]..."
    set wrapper_path [make_wrapper -files $bd_files -top]
    
    if {[file exists $wrapper_path]} {
        set fp [open $wrapper_path r]
        set content [read $fp]
        close $fp
        
        set wrapper_entity [file rootname [file tail $wrapper_path]]
        set ext [file extension $wrapper_path]
        set top_file [file normalize "./src/hdl/top${ext}"]
        set bd_wrapper_file [file normalize "./src/hdl/${wrapper_entity}${ext}"]

        # Ensure the directory exists
        file mkdir [file dirname $top_file]

        # Always sync the BD subsystem wrapper (e.g. system.vhd)
        set fp [open $bd_wrapper_file w]
        puts $fp $content
        close $fp
        puts "📦 Synced BD subsystem wrapper to: $bd_wrapper_file"
        
        if {![file exists $top_file]} {
            # Bootstrap top-level only if missing
            regsub -all $wrapper_entity $content "top" new_content
            puts "🌱 No top-level found. Creating initial bootstrap top-level..."
            set fp [open $top_file w]
            puts $fp $new_content
            close $fp
            puts "✅ Created bootstrap top-level at: $top_file"
        } else {
            puts "✅ Master top-level exists ($top_file). Instantiate 'entity work.${wrapper_entity}' inside top${ext}."
        }
    }
}

# --- UI REFRESH ---
catch { remove_gui_custom_commands SyncFramework }
catch { remove_gui_custom_commands SyncFramework_v2 }
catch { remove_gui_custom_commands SyncFramework_v3 }

if {[get_gui_custom_commands SyncFramework_Final] == ""} {
    create_gui_custom_command -name "SyncFramework_Final" \
        -menu_name "Sync to Framework" \
        -command "::sync_bd" \
        -show_on_toolbar \
        -description "Saves the current Block Design into the framework scripts folder"
}

# --- Load the actual Block Design script ---
set bd_script "./board_configs/${board_name}_bd.tcl"
if {[file exists $bd_script]} {
    source $bd_script
    set_property target_language $target_lang [current_project]
    set_property simulator_language Mixed [current_project]
    puts "⚙️  Framework: Forced target language to $target_lang"
}

puts "✅ Framework Active: Use the 'Sync to Framework' button or type 'sync_bd'."
